version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./files:/files
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: mikolatero/php5.6-fpm-alpine
        volumes:
            - ./files:/files
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
